export const officialTeams2026 = [
  { name: 'Duke', region: 'East', seed: 1 },
  { name: 'Siena', region: 'East', seed: 16 },
  { name: 'Ohio State', region: 'East', seed: 8 },
  { name: 'TCU', region: 'East', seed: 9 },
  { name: "St. John's", region: 'East', seed: 5 },
  { name: 'Northern Iowa', region: 'East', seed: 12 },
  { name: 'Kansas', region: 'East', seed: 4 },
  { name: 'Cal Baptist', region: 'East', seed: 13 },
  { name: 'Louisville', region: 'East', seed: 6 },
  { name: 'South Florida', region: 'East', seed: 11 },
  { name: 'Michigan State', region: 'East', seed: 3 },
  { name: 'North Dakota State', region: 'East', seed: 14 },
  { name: 'UCLA', region: 'East', seed: 7 },
  { name: 'UCF', region: 'East', seed: 10 },
  { name: 'UConn', region: 'East', seed: 2 },
  { name: 'Furman', region: 'East', seed: 15 },

  { name: 'Arizona', region: 'West', seed: 1 },
  { name: 'Long Island', region: 'West', seed: 16 },
  { name: 'Villanova', region: 'West', seed: 8 },
  { name: 'Utah State', region: 'West', seed: 9 },
  { name: 'Wisconsin', region: 'West', seed: 5 },
  { name: 'High Point', region: 'West', seed: 12 },
  { name: 'Arkansas', region: 'West', seed: 4 },
  { name: 'Hawaii', region: 'West', seed: 13 },
  { name: 'BYU', region: 'West', seed: 6 },
  { name: 'Texas / NC State winner', region: 'West', seed: 11 },
  { name: 'Gonzaga', region: 'West', seed: 3 },
  { name: 'Kennesaw State', region: 'West', seed: 14 },
  { name: 'Miami (FL)', region: 'West', seed: 7 },
  { name: 'Missouri', region: 'West', seed: 10 },
  { name: 'Purdue', region: 'West', seed: 2 },
  { name: 'Queens (N.C.)', region: 'West', seed: 15 },

  { name: 'Florida', region: 'South', seed: 1 },
  { name: 'Prairie View A&M / Lehigh winner', region: 'South', seed: 16 },
  { name: 'Clemson', region: 'South', seed: 8 },
  { name: 'Iowa', region: 'South', seed: 9 },
  { name: 'Vanderbilt', region: 'South', seed: 5 },
  { name: 'McNeese', region: 'South', seed: 12 },
  { name: 'Nebraska', region: 'South', seed: 4 },
  { name: 'Troy', region: 'South', seed: 13 },
  { name: 'North Carolina', region: 'South', seed: 6 },
  { name: 'VCU', region: 'South', seed: 11 },
  { name: 'Illinois', region: 'South', seed: 3 },
  { name: 'Penn', region: 'South', seed: 14 },
  { name: "Saint Mary's", region: 'South', seed: 7 },
  { name: 'Texas A&M', region: 'South', seed: 10 },
  { name: 'Houston', region: 'South', seed: 2 },
  { name: 'Idaho', region: 'South', seed: 15 },

  { name: 'Michigan', region: 'Midwest', seed: 1 },
  { name: 'UMBC / Howard winner', region: 'Midwest', seed: 16 },
  { name: 'Georgia', region: 'Midwest', seed: 8 },
  { name: 'Saint Louis', region: 'Midwest', seed: 9 },
  { name: 'Texas Tech', region: 'Midwest', seed: 5 },
  { name: 'Akron', region: 'Midwest', seed: 12 },
  { name: 'Alabama', region: 'Midwest', seed: 4 },
  { name: 'Hofstra', region: 'Midwest', seed: 13 },
  { name: 'Tennessee', region: 'Midwest', seed: 6 },
  { name: 'Miami (Ohio) / SMU winner', region: 'Midwest', seed: 11 },
  { name: 'Virginia', region: 'Midwest', seed: 3 },
  { name: 'Wright State', region: 'Midwest', seed: 14 },
  { name: 'Kentucky', region: 'Midwest', seed: 7 },
  { name: 'Santa Clara', region: 'Midwest', seed: 10 },
  { name: 'Iowa State', region: 'Midwest', seed: 2 },
  { name: 'Tennessee State', region: 'Midwest', seed: 15 },
] as const;
